name: Update the UML Diagrams

# CINTENT >> MANUAL_TRIGGER
# on:
#   workflow_dispatch:
#   schedule:
#     - cron:  '0 12 * * 1'
on: [repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@a606c80c34ec190c6a20dea33d6d58ddb6c4e0cc

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      # CINTENT >> REMOVE_GIT
      # - name: Configure Git Identity
      #   run: |
      #     git config user.name 'github-actions[bot]'
      #     git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update the UML Diagrams
        run: |
          sudo apt-get update && sudo apt-get install -y graphviz
          make uml

      - name: Detect UML changes
        id: changes
        run: |
          git add docs/source/uml/*.png
          if git diff --staged --exit-code; then
            echo "No changes to commit"
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          else
            echo "changes_exist=true" >> $GITHUB_OUTPUT
          fi

      # CINTENT >> REMOVE_UPLOADS
      # - name: Create PR for changes
      #   if: steps.changes.outputs.changes_exist == 'true'
      #   run: |
      #     git checkout -b update-uml-diagrams
      #     git commit -m "Update UML Diagrams"
      #     git push -u origin update-uml-diagrams
      #     gh pr create \
      #       --base main \
      #       --title "Update UML Diagrams" \
      #       --body "This PR updates the UML diagrams

      #       This PR was created automatically by the [UML workflow](https://github.com/pymc-labs/pymc-marketing/blob/main/.github/workflows/uml.yml).

      #       See the logs [here](https://github.com/pymc-labs/pymc-marketing/actions/workflows/uml.yml) for more details." \
      #       --label "no releasenotes" \
      #       --reviewer "williambdean,juanitorduz"
      #   env:
      #     GH_TOKEN: ${{ github.token }}

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
